### ISSUE TITLE
v1.1.1 fails with 'Cannot read properties of undefined (reading 'setFailed')'

### ISSUE THREAD

**Issue by MorrisonCole** [zentered/vercel-preview-url#135]
**Describe the bug**
Upgrading from `v1.0.7 -> v1.1.1` with no other changes causes the action to fail with:

```
/home/runner/work/_actions/zentered/vercel-preview-url/v1.1.1/dist/index.js:11451
        core_default().setFailed(error.message)
                      ^
TypeError: Cannot read properties of undefined (reading 'setFailed')
    at run (/home/runner/work/_actions/zentered/vercel-preview-url/v1.1.1/dist/index.js:11451:23)
    at /home/runner/work/_actions/zentered/vercel-preview-url/v1.1.1/dist/index.js:11455:5
    at /home/runner/work/_actions/zentered/vercel-preview-url/v1.1.1/dist/index.js:11456:5
    at Object.<anonymous> (/home/runner/work/_actions/zentered/vercel-preview-url/v1.1.1/dist/index.js:11460:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:9[8](https://github.com/MorrisonCole/morrisoncole.co.uk/actions/runs/3492947514/jobs/5847238633#step:4:9)1:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/MorrisonCole/morrisoncole.co.uk/actions/runs/3492947514/jobs/5847238633#step:4:13))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:[17](https://github.com/MorrisonCole/morrisoncole.co.uk/actions/runs/3492947514/jobs/5847238633#step:4:18):47
```

**To Reproduce**
My project is open-source so should be able to check out the configuration etc. here: https://github.com/MorrisonCole/morrisoncole.co.uk/actions/runs/3492947514/jobs/5847238633

**Comment by PatrickHeneise** [comment]
Thanks for reporting this. I'll have a look

**Comment by MorrisonCole** [comment]
Oh nice, that works and you made the team ID optional too! Thanks! 🎉
